import { Cairo } from "next/font/google";
import "./globals.css";
import "../components/styles.css";
import Navbar from "@/components/Navbar";
import Providers from "./Providers";


const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Print Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cairo.variable} antialiased min-h-screen`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
