import Loader from "@/components/dashboard/Loader";
import Navbar from "@/components/dashboard/Navbar";
import Sidebar from "@/components/dashboard/Sidebar";
import RequestPopup from "@/components/dashboard/RequestPopup";
import ClientLayout from "./ClientLayout";

export const metadata = {
  title: "Print Administation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientLayout>
      <div className="min-h-screen">
        <Navbar />
        <div className="flex">
          <div
            className="sticky top-[56px] z-40 "
            style={{ height: "calc(100vh - 90px)" }}
          >
            <Sidebar />
          </div>
          <main className="flex-1">
            {children}
            <RequestPopup />
          </main>
        </div>
        <Loader />
      </div>
    </ClientLayout>
  );
}
