import Navbar from "@/components/dashboard/layout/Navbar";
import Sidebar from "@/components/dashboard/layout/Sidebar";
import ClientLayout from "./ClientLayout";

export const metadata = {
  title: "Print Administation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientLayout>
      <div>
        <Navbar />
        <div className="flex">
          <div
            className="sticky top-[56px] z-40 "
            style={{ height: "calc(100vh - 90px)" }}
          >
            <Sidebar />
          </div>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </div>
    </ClientLayout>
  );
}
