import Navbar from "@/components/dashboard/Navbar";
import Sidebar from "@/components/dashboard/Sidebar";

export const metadata = {
  title: "Print Administation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen">
    <Navbar />
    <div className="flex flex-1">
      <div className="sticky top-[56px] z-40 " style={{ height :"calc(100vh - 90px)"}}>
        <Sidebar />
      </div>
      <main className="flex-1 overflow-y-auto">{children}</main>
    </div>
  </div>
  );
}
