import Loader from "@/components/dashboard/Loader";
import Navbar from "@/components/dashboard/Navbar";
import Sidebar from "@/components/dashboard/Sidebar";
import ViewReqPopup from "@/components/dashboard/ViewReqPopup";
import AuthChecker from "../AuthChecker";

export const metadata = {
  title: "Print Administation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen">
      <AuthChecker>
        <Navbar />
        <div className="flex">
          <div
            className="sticky top-[56px] z-40 "
            style={{ height: "calc(100vh - 90px)" }}
          >
            <Sidebar />
          </div>
          <main className="flex-1">
            {children}
            <ViewReqPopup />
          </main>
        </div>
        <Loader />
      </AuthChecker>
    </div>
  );
}
