export const requests = [
  {
    _id: 0,
    teacher: "belkacemi ahmed",
    type: "TP",
    quantity: "30",
    status: "completed",
  },
  {
    _id: 1,
    teacher: "nadia benali",
    type: "TD",
    quantity: "20",
    status: "pending",
  },
  {
    _id: 2,
    teacher: "amine kaci",
    type: "Cours",
    quantity: "50",
    status: "refused",
  },
  {
    _id: 3,
    teacher: "sara amrani",
    type: "TP",
    quantity: "15",
    status: "completed",
  },
  {
    _id: 4,
    teacher: "kamel yahia",
    type: "TD",
    quantity: "25",
    status: "completed",
  },
  {
    _id: 5,
    teacher: "layla ferhat",
    type: "Cours",
    quantity: "40",
    status: "pending",
  },
  {
    _id: 6,
    teacher: "farid ziani",
    type: "TP",
    quantity: "35",
    status: "approved",
  },
  {
    _id: 7,
    teacher: "karima charef",
    type: "TD",
    quantity: "10",
    status: "completed",
  },
  {
    _id: 8,
    teacher: "yassine ouhib",
    type: "Cours",
    quantity: "45",
    status: "pending",
  },
  {
    _id: 9,
    teacher: "hana boudiaf",
    type: "TP",
    quantity: "20",
    status: "refused",
  },
  {
    _id: 10,
    teacher: "nabil merbah",
    type: "TD",
    quantity: "30",
    status: "completed",
  },
  {
    _id: 11,
    teacher: "asmaa ait said",
    type: "Cours",
    quantity: "55",
    status: "pending",
  },
];
